require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
  - 'spec/spec_helper.rb'
  - 'bin/chess'

Metrics/BlockLength:
  Exclude:
  - './spec/**/*.rb'

Security/MarshalLoad:
  Exclude:
  - 'lib/chess/serialize.rb'
