---
inherit_from:
  - https://relaxed.ruby.style/rubocop.yml

require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'spec/spec_helper.rb'
    - 'bin/*'
  NewCops: enable

Metrics/BlockLength:
  Exclude:
  - './spec/**/*.rb'

Security/MarshalLoad:
  Exclude:
  - 'lib/chess/serialize.rb'
