---
inherit_from:
  - https://relaxed.ruby.style/rubocop.yml

require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'bin/chess'
  NewCops: enable

Metrics/BlockLength:
  Exclude:
  - './spec/**/*.rb'

Security/MarshalLoad:
  Exclude:
  - 'lib/chess/serialize.rb'

RSpec/ExampleLength:
  Exclude:
  - 'spec/pieces/queen/black_queen_spec.rb'
  - 'spec/pieces/queen/white_queen_spec.rb'
